name: AzureSpringCloud
on: push
env:
  AZURE_SUBSCRIPTION: ${{ secrets.SUBSCRIPTION_NAME }}
  RESOURCE_GROUP: rg-ascdev-test
  SPRING_CLOUD_INSTANCE_NAME: ascpetclinicentdev1

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with soruce code
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install ASC extension
        run: |
          az extension add -s https://ascprivatecli.blob.core.windows.net/enterprise/spring_cloud-2.7.0a1-py3-none-any.whl -y

      - name: Deploy
        run: |
          az account set -s ${{ env.AZURE_SUBSCRIPTION }}
          az config set defaults.group=$GROUP
          az config set defaults.spring-cloud=$SPRING_CLOUD_INSTANCE_NAME

          az spring-cloud app deploy -n vets-service --jar-path ${{ github.workspace }}/target/spring-petclinic-vets-service-2.5.1.jar